### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by daniellaera** [Madhawa97/SSDLifeCalc#2]
When I execute I have this error

  File "/Users/user_name/calc.py", line 24, in <module>
    life_time = round(avail_space /
ZeroDivisionError: float division by zero

it seems that the input in days is not taken in consideration so for the algorithm is equal to 0

**Comment by Madhawa97** [comment]
Hi, thanks for the feedback. yeah seems something is wrong. this is what I get when I enter 0 as "No. of days from the creation of first.txt file?"
<img width="766" alt="Screenshot 2021-03-07 at 16 02 37" src="https://user-images.githubusercontent.com/70215958/110236885-8df18080-7f5e-11eb-9ee4-e521b90f6c7a.png">
"

**Comment by daniellaera** [comment]
weird I got this! where's my issue

<img width="506" alt="Screenshot 2021-03-07 at 11 40 44" src="https://user-images.githubusercontent.com/8995710/110237049-ff6b0800-7f39-11eb-8bba-d3cb6b37e40f.png">

can you copy paste your actual python script?
I might have a format problem

**Comment by daniellaera** [comment]
<img width="527" alt="Screenshot 2021-03-07 at 11 45 14" src="https://user-images.githubusercontent.com/8995710/110237173-9a63e200-7f3a-11eb-925b-3008ef099dd0.png">

 is ok now, missed 2 first lines in my script 😭😂

**Comment by Madhawa97** [comment]
😃 glad it worked. feel free to keep your code up to date.

**Comment by Madhawa97** [comment]
Yes. I'm totally okay with that 😄

**Comment by Madhawa97** [comment]
I fixed a few issues with the formatting. additionally, Now running the python file is enough every time you wanna check. the updated "new.txt" file being created and replaced by the python script itself.
